<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!--
        1.async函数
          ===>返回的是一个Promise对象
          ===>返回Promise的状态由函数内部的返回值决定

        2.await表达式
          ===>await右侧的表达式一般为Promise对象，但也可以是其他值
          ===>如果右侧的表达式是一个Promise对象，则await返回的值是成功的value
          ===>如果右侧的表达式不是Promise对象，则await返回的值是该值

        3.注意事项
          ===>await必须写在async函数内部，但async函数中可以没有await表达式
          ===>await不能处理失败状态的Promise，只能用try{}catch{}来捕获失败或者异常
    -->
    <script>
        //async函数
        //async函数返回的是一个Promise对象
        //返回的Promise的结果由async函数执行的结果决定
        async function fn1() {
            //return 1
            //throw 2
            return Promise.resolve(3)
        }
        const result = fn1();
        console.log(result);
        result.then(
            value => console.log(value),
            reason => console.log(reason)
        )

        //await表达式
        function fn2() {
            return new Promise((resolve, reject) => {
                //setTimeout(() => {
                //    resolve('Promise对象')
                //    //reject('失败Promise')
                //}, 1000)
                resolve(111)
            })
        }
        function fn3() {
            return Promise.resolve('11');
        }

        async function fn4() {
            try {
                fn2().then(value=>console.log(value))
                const result = await fn2();//await右侧表达为Promise时，得到的结果就是这个Promise的value值
                const result1 = await fn3();//await右侧表达不是Promise对象时，得到的结果就是这个本身
                console.log(result, result1);
            } catch (error) {
                console.log(error);
            }
        }
            fn4()
    </script>
</body>

</html>